services:
  # A Docker web service
  - type: web
    name: webapp
    env: static
    buildCommand: npm install; npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_SERVER_URL
        fromService:
          name: tictactoe-server
          type: web
          envVarKey: RENDER_EXTERNAL_URL