services:
  # A Docker web service
  - type: web
    name: webapp

 envVars:
      - key: REACT_APP_HOST_NAME
        fromService:
          name: tictactoe-server
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME